### ISSUE TITLE
 What is the status of the project?

### ISSUE THREAD

**Issue by NikitaIT** [geoffrey-hill-tutamantic/rapid-threat-model-prototyping-docs#1]
- Finished?
- In progress?
- Industry best practices?
- What's better?

P.S. Where can I find out more about this, any recommendations?

**Comment by geoffrey-hill-tutamantic** [comment]
Hi NikitaIT, apologies for not getting back to you sooner. Here are my answers to your bullet points:

- Finished?
- [GH] This is a continuing project and I plan on updating the repo with more information this year as the practitioners give feedback

- In progress?
- [GH] Yes, and I will be providing more data and practices as they get sorted

- Industry best practices?
- [GH] At the moment, threat modeling doesn't have "best practices"; there are many different ways to approach threat modeling... I created mine to enable teams to roll out a way to quickly do threat models in limited-time situations (which in my experience are most development environments... hence the lack of threat modeling.)

- What's better?
- [GH] This is a strange question to ask because I obviously believe my methodology is an advance on doing threat model activity. However, if you are interested in learning other ways to do threat modeling, read the Wikipedia article on 'Threat Model' here (https://en.wikipedia.org/wiki/Threat_model). My methodology improves upon STRIDE.

**Comment by geoffrey-hill-tutamantic** [comment]
I forgot the P.S.

Just watch one or more of the videos I have posted going over Rapid Threat Model Prototyping (RTMP). If you are further interested, please send an email to support01 at the tutamantic.com domain.

**Comment by NikitaIT** [comment]
Thanks for the answer. I, if you're interested, came here thanks to [tl; dr security blog](https://tldrsec.com/), where there was a [link](https://github.com/secmerc/materialize-threats) to the implementation of RTMP + drow.io. And I found your videos very helpful. Good luck.
